export interface Project {
  slug: string;
  name: string;
  value: string;
  year: string;
  description: string;
  category: 'Industrial' | 'Infrastructure' | 'Warehousing';
  status: 'Ongoing' | 'Completed';
  client: string;
  scope: string[];
  imageUrl: string;
  gallery?: string[];
}

export const projects: Project[] = [
  {
    slug: 'hitachi-hi-rel',
    name: 'Hitachi Hi-Rel Power Electronics Ltd',
    value: '₹2.20 Cr',
    year: '2024-2025',
    description: 'Advanced industrial electronics manufacturing facility construction.',
    category: 'Industrial',
    status: 'Ongoing',
    client: 'Hitachi Hi-Rel',
    scope: ['RCC Works', 'Structural Steel', 'Flooring', 'MEP Coordination'],
    imageUrl: '/projects/hitachi/cover.jpg',
    gallery: [
      '/projects/hitachi/gallery-1.jpg',
      '/projects/hitachi/gallery-2.jpg',
      '/projects/hitachi/gallery-3.jpg',
    ],
  },
  {
    slug: 'nectar-engineering',
    name: 'Nectar Engineering',
    value: '₹1.80 Cr',
    year: '2024-2025',
    description: 'Precision engineering workshop and administrative block.',
    category: 'Industrial',
    status: 'Ongoing',
    client: 'Nectar Engineering',
    scope: ['Foundation', 'Structural Steel Fabrication', 'Roofing'],
    imageUrl: '/projects/nectar/cover.jpg',
    gallery: [
      '/projects/nectar/gallery-1.jpg',
      '/projects/nectar/gallery-2.jpg',
    ],
  },
  {
    slug: 'plot-20-sanand',
    name: 'Plot No. 20 Sanand',
    value: '₹1.15 Cr',
    year: '2024-2025',
    description: 'Multi-purpose industrial shed construction at Sanand GIDC.',
    category: 'Industrial',
    status: 'Ongoing',
    client: 'Private Client',
    scope: ['Earthwork', 'PCC/RCC', 'Structural Shed'],
    imageUrl: '/projects/plot-20-sanand/cover.jpg',
  },
  {
    slug: 'siddhi-premises',
    name: 'Siddhi Industrial Services Premises',
    value: '₹0.95 Cr',
    year: '2023-2025',
    description: 'Expansion and modernization of own operations base.',
    category: 'Infrastructure',
    status: 'Ongoing',
    client: 'Siddhi Industrial Services',
    scope: ['Internal Roads', 'Drainage', 'Office Interior Construction'],
    imageUrl: '/projects/siddhi-premises/cover.jpg',
  },
  {
    slug: 'uneco',
    name: 'UNECO',
    value: '₹1.05 Cr',
    year: '2023',
    description: 'Turnkey industrial plant development.',
    category: 'Industrial',
    status: 'Completed',
    client: 'UNECO',
    scope: ['Civil Works', 'Steel Structure'],
    imageUrl: '/projects/uneco/cover.jpg',
  },
  {
    slug: 'supreme-power',
    name: 'Supreme Power',
    value: '₹1.10 Cr',
    year: '2023',
    description: 'Substation and power facility infrastructure.',
    category: 'Infrastructure',
    status: 'Completed',
    client: 'Supreme Power',
    scope: ['Specialized Foundations', 'Safety Walls'],
    imageUrl: '/projects/supreme-power/cover.jpg',
  },
  {
    slug: 'energy-mission',
    name: 'Energy Mission',
    value: '₹0.85 Cr',
    year: '2022',
    description: 'Manufacturing unit for energy equipment.',
    category: 'Industrial',
    status: 'Completed',
    client: 'Energy Mission',
    scope: ['Civil Construction', 'Utility Lines'],
    imageUrl: '/projects/energy-mission/cover.jpg',
  },
  {
    slug: 'johnson-screens',
    name: 'Johnson Screens',
    value: '₹0.80 Cr',
    year: '2022',
    description: 'Industrial filter manufacturing plant extension.',
    category: 'Industrial',
    status: 'Completed',
    client: 'Johnson Screens',
    scope: ['RCC Flooring', 'Extension shed'],
    imageUrl: '/projects/johnson-screens/cover.jpg',
  },
  {
    slug: 'vital-wellness',
    name: 'Vital Wellness',
    value: '₹1.10 Cr',
    year: '2021',
    description: 'Wellness product distribution warehouse.',
    category: 'Warehousing',
    status: 'Completed',
    client: 'Vital Wellness',
    scope: ['VDF Flooring', 'Steel Racks foundation', 'Warehousing shed'],
    imageUrl: '/projects/vital-wellness/cover.jpg',
  },
  {
    slug: 'alp-nishikawa',
    name: 'ALP Nishikawa',
    value: '₹0.85 Cr',
    year: '2021',
    description: 'Automotive component plant expansion.',
    category: 'Industrial',
    status: 'Completed',
    client: 'ALP Nishikawa',
    scope: ['Industrial Shed', 'Machine Foundations'],
    imageUrl: '/projects/alp-nishikawa/cover.jpg',
  },
  {
    slug: 'sharda-motors',
    name: 'Sharda Motors',
    value: '₹1.15 Cr',
    year: '2020',
    description: 'Exhaust system manufacturing unit expansion.',
    category: 'Industrial',
    status: 'Completed',
    client: 'Sharda Motors',
    scope: ['High-load Foundations', 'Internal Paving'],
    imageUrl: '/projects/sharda-motors/cover.jpg',
  },
  {
    slug: 'mahle-anand',
    name: 'Mahle Anand Thermal Systems',
    value: '₹1.10 Cr',
    year: '2020',
    description: 'Thermal systems production facility infrastructure.',
    category: 'Industrial',
    status: 'Completed',
    client: 'Mahle Anand',
    scope: ['RCC Slabs', 'Utility Trenches'],
    imageUrl: '/projects/mahle-anand/cover.jpg',
  }
];